// src/constants/disposableEmailDomains.js
// List of disposable email domains for validation

export const DISPOSABLE_EMAIL_DOMAINS = [
  // Common disposable email domains
  'mailinator.com', 
  'trashmail.com', 
  'guerrillamail.com', 
  'tempmail.com', 
  '10minutemail.com', 
  'yopmail.com',
  'disposablemail.com', 
  'mailnesia.com', 
  'mailcatch.com',
  'temp-mail.org', 
  'spamgourmet.com', 
  'dispostable.com',
  'mintemail.com', 
  'mailnull.com', 
  'mytrashmail.com',
  'throwawaymail.com', 
  'sharklasers.com', 
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'wegwerfemail.de', 
  'tempmail.net', 
  'getnada.com',
  'fakeinbox.com',
  'mailforspam.com',
  'emailfake.com',
  'tempinbox.com',
  'discard.email',
  'maildrop.cc',
  'harakirimail.com',
  'mailcatch.com',
  'mailinator.co',
  'mailinator.net',
  'temp-mail.io',
  'tempemail.co',
  'throwawaymail.com',
  'tempmailer.com',
  'fakemailgenerator.com'
];
